services:
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /opt/DockerSwarmData/thelounge/config:/config
    ports:
      - 7000:9000 # <Host Port>:<Container Port>
    restart: unless-stopped

