# Run with:
# ansible-playbook InstallGCC.yml

---
- name: Install GC
  hosts: all
  tasks:

  - name: Install GCC packages on OpenSUSE/SUSE Linux
    zypper:
      name: gcc15*
      state: present

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/bin/gcc-15
      dest: /usr/bin/gcc
      state: link

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/bin/g++-15
      dest: /usr/bin/g++
      state: link

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/bin/gcc-15
      dest: /usr/bin/cc
      state: link

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/bin/g++-15
      dest: /usr/bin/c++
      state: link

