# Run with
# ansible-playbook SetupJellyfin.yml
# https://jellyfin.org/

---
- name: Setup Jellyfin
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: Create directory for data
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /opt/DockerSwarmData/jellyfin
      - /opt/DockerSwarmData/jellyfin/config
      - /opt/DockerSwarmData/jellyfin/tvshows
      - /opt/DockerSwarmData/jellyfin/movies
      - /mnt/allwrite
      - /mnt/allwrite/family
      - /mnt/allwrite/favorites
      - /mnt/allwrite/new
      - /mnt/allwrite/brittany
      - /root/docker
      - /root/docker/jellyfin

  - name: Copy the docker-compose file with owner and permissions
    ansible.builtin.copy:
      src: docker-compose.yml
      dest: /root/docker/jellyfin
      owner: ajorians
      group: users
      mode: 0777

  - name: Deploy Jellyfin from a compose file
    community.docker.docker_compose_v2:
      project_src: /root/docker/jellyfin

  - name: Make Apache VHost file
    ansible.builtin.copy:
      dest: /etc/apache2/vhosts.d/jellyfin.conf
      force: false
      content: |
        <VirtualHost *:80>
          ServerName jellyfin.orians.org
          ServerAlias jellyfin.stage.orians.org jellyfin
          ProxyPass / http://127.0.0.1:8096/
          ProxyPassReverse / http://127.0.0.1:8096/
        </VirtualHost>
    notify:
    - Restart Apache2 service

# I got SyncPlay working by adding the following to the SSL config file
# RewriteCond %{HTTP:Upgrade} =websocket
# RewriteRule /(.*) ws://127.0.0.1:8096/socket/$1 [P,L]
# RewriteCond %{HTTP:Upgrade} !=websocket
# RewriteRule /(.*) http://127.0.0.1:8096/$1 [P,L]

  handlers:
    - name: Restart Apache2 service
      ansible.builtin.systemd:
        state: restarted
        name: apache2

