version: "3"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /opt/DockerSwarmData/resiliosync/config:/config
      - /opt/DockerSwarmData/resiliosync/downloads:/downloads
      - /opt/DockerSwarmData/resiliosync/sync:/mnt
      - /mnt/backups:/backups
    ports:
      - 9200:8888
      - 9201:55555
    restart: unless-stopped
